spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true     
      httpclient:
        ssl:
          use-insecure-trust-manager: true
  security:
    user:
      name: apiuser
      password: apiuser
      roles:
      - ADMIN
      - USER
  datasource:
    url: jdbc:mysql://GBSMIXDEV01.UK.OUP.COM:3306/DB_APISECURITY
    hikari:
      connection-init-sql: SELECT SYSDATE()
      maximum-pool-size: 10
      minimum-idle: 5
    #username: apisecurity
    #password: Passw0rd@1234    
server:
   port: 443
   ssl:
      key-store: classpath:api-dev-internal.jks
      key-store-password: User@1234
      #keyStoreType: PKCS12
      keyAlias: api-dev-internal
eureka:
  client:
    service-url:
      defaultZone: http://10.128.3.135:8761/eureka/
    register-with-eureka: false
  instance:
    prefer-ip-address: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
---
spring:
  profiles: dev
server:
   port: 443
   ssl:
      key-store: classpath:api-dev-internal.jks
      key-store-password: User@1234
      #keyStoreType: PKCS12
      keyAlias: api-dev-internal
eureka:
  client:
    service-url:
      defaultZone: http://dev-oupeureka:8761/eureka/
  instance:
   prefer-ip-address: true
---
spring:
  profiles: uat
  datasource:
    url: jdbc:mysql://GBSMIXUAT01.UK.OUP.COM:3306/DB_APISECURITY
    hikari:
      connection-init-sql: SELECT SYSDATE()
      maximum-pool-size: 10
      minimum-idle: 5 
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://uat-oupeureka:8761/eureka/
  instance:
   prefer-ip-address: true
---
spring:
  profiles: prod
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://prod-oupeureka:8761/eureka/
  instance:
   prefer-ip-address: true